# Bash cmd: deploy.sh v1.0.1          run it in Git Bash
#!/bin/bash

# 1. SETUP VARIABLES
VERSION=${1:-v1.0}
IMAGE_NAME="rpajany/pos-app"
BACKUP_DIR="./backups"
TIMESTAMP=$(date +%Y%m%d_%H%M%S)

# Target the 'db' service specifically as the primary backup source
# We use 'docker ps' to find the exact name generated by your folder
MONGO_CONTAINER=$(docker ps --filter "name=db" --format '{{.Names}}' | head -n 1)

echo "------------------------------------------"
echo "🚀 STARTING REPLICA SET BACKUP & DEPLOY"
echo "------------------------------------------"

# 2. DATABASE BACKUP
if [ -z "$MONGO_CONTAINER" ]; then
    echo "❌ ERROR: Could not find your 'db' container. Is 'docker-compose up' running?"
    exit 1
else
    echo "💾 Step 1: Backing up MongoDB Primary ($MONGO_CONTAINER)..."
    mkdir -p $BACKUP_DIR
    # Using mongodump on the primary node captures the data for the whole set
    docker exec $MONGO_CONTAINER mongodump --archive --gzip > "$BACKUP_DIR/full_set_backup_$TIMESTAMP.gz"
    echo "✅ Backup saved to: $BACKUP_DIR/full_set_backup_$TIMESTAMP.gz"
fi

# 3. BUILD IMAGE
echo "🛠️  Step 2: Building App Image ($VERSION)..."
docker build -t $IMAGE_NAME:$VERSION .
docker tag $IMAGE_NAME:$VERSION $IMAGE_NAME:latest

# 4. PUSH TO DOCKER HUB
echo "☁️  Step 3: Pushing to Docker Hub..."
docker push $IMAGE_NAME:$VERSION
docker push $IMAGE_NAME:latest

echo "------------------------------------------"
echo "✨ PROCESS COMPLETE!"
echo "Your app is updated and your Replica Set data is backed up."
echo "------------------------------------------"